### ISSUE TITLE
Incorrect course evaluation score

### ISSUE THREAD

**Issue by swekung** [toasterbag/course-portal#1]
When there has been only one instance of a course the survey analaysis is broken. The overall impression score is wrong and none of the other scores appear.
Examples can be seen in the courses MMS135 and TDA233.

**Comment by toasterbag** [comment]
Thanks for the issue! There was a problem with the new Chart.js plugin that is used to display the examiners. It should be fixed in the latest commit, but since it was a bug with the frontend it won't show up in this repo.

Extra thanks for providing examples!
